language: erlang

os:
  - linux

otp_release:
   - 20.3
   - 21.3

notifications:
  email: rtb-team+travis@adroll.com

script:
  - rebar3 local upgrade
  - export PATH=/home/travis/.cache/rebar3/bin:$PATH
  - rebar3 --version
  - erl -version
  - rebar3 test
  - git --no-pager diff
  - if [[ $(git --no-pager diff) ]]; then echo "Your code is not properly formatted, run rebar3 format on it"; exit 999; fi
